FROM hpc-io-analysis-base:latest

ARG DFTRACER_VERSION=1.0.5

ENV DFTRACER_ENABLE=1 \
    DFTRACER_INC_METADATA=1 \
    DFTRACER_LOG_FILE=/var/log/dftracer

RUN mkdir -p ${DFTRACER_LOG_FILE}

RUN pip install --upgrade pip && \
    pip install pydftracer==${DFTRACER_VERSION}
