FROM recorder-analysis-base:latest

ARG DARSHAN_VERSION=3.4.5
ARG INSTALL_PREFIX=/usr/local

ENV LD_LIBRARY_PATH=/usr/local/lib

WORKDIR /opt

RUN . ./scripts/installation.sh && \
    install_darshan ${INSTALL_PREFIX} ${DARSHAN_VERSION}

ENV DXT_ENABLE_IO_TRACE=1 \
    LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH}

RUN pip install --upgrade pip && \
    pip install darshan==${DARSHAN_VERSION}
